### ISSUE TITLE
HDMI Source

### ISSUE THREAD

**Issue by darpet75** [filimonic/Kodi.Screensaver.TurnOffLGTV#8]
It is possible to run screen saver only if HDMI Source is Raspberry and not Live TV?

**Comment by filimonic** [comment]
AFAIK, It is not possible to detect if HDMI input of TV is currently active
from screensaver addon (technically it is possible, but addons have no
access to this method, because we do not have any hdmi functions in Kodi's
addon API), so, screensaver can not see if you are watching KODI or not.

There are three ways to detect if TV is showing Kodi:
1. Through HDMI interface, however HDMI and CEC functuons are not present
in Kodi API
2. Through TV' TCP protocol. Dont know if possible.
3. Through 3rd party software (that will do same thung that HDMI API does)

No one of theese ways is tested nor umplemented any way in known software

27 Авг 2017 г. 11:51 пользователь "darpet75" <notifications@github.com>
написал:

**Comment by darpet75** [comment]
thanks. i will want to ask you some questions for TV TCP protocol but i do not know if this is the correct way.

**Comment by filimonic** [comment]
Sorry I do not know it at all. TV power off is done based on info I got by
some sniffing and internet searching

30 Авг 2017 г. 9:46 пользователь "darpet75" <notifications@github.com>
написал:
